# Generated by Django 5.0.6 on 2024-06-21 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0003_userdetail"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserDetail",
        ),
    ]
