# Generated by Django 5.0.6 on 2024-09-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0003_shortenedurls_click_statistic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statistic",
            name="device_os",
            field=models.CharField(max_length=10),
        ),
    ]
