# Generated by Django 5.0.6 on 2024-06-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0004_delete_userdetail"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="full_name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
