# Generated by Django 5.0.6 on 2024-07-12 01:37

import django.db.models.deletion
import shortener.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0005_users_full_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShortenedUrls",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nick_name", models.CharField(max_length=100)),
                ("target_url", models.CharField(max_length=2000)),
                (
                    "shortened_url",
                    models.CharField(
                        default=shortener.models.ShortenedUrls.rand_string, max_length=6
                    ),
                ),
                (
                    "created_via",
                    models.CharField(
                        choices=[("web", "Website"), ("telegram", "Telegram")],
                        default="web",
                        max_length=8,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
